# Generated by Django 5.0.7 on 2024-08-31 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loong_items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('color_name', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('color', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('cost', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('store', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
