# Generated by Django 5.0.7 on 2024-08-31 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loong_items',
            table='loong_items',
        ),
    ]
