const privacy_policy = `Lorem ipsum dolor sit amet, consectetur adipiscing elit. In sed lorem felis. Nulla orci elit, tempor et fringilla vel, pretium et turpis. Aenean augue arcu, placerat non egestas non, tristique non tellus. Fusce quis purus enim. Etiam vehicula, ante mollis mattis semper, nisi ex commodo quam, ac iaculis nisl nulla vitae mi. Suspendisse luctus suscipit velit, sed pretium felis cursus porttitor. Aliquam semper augue at metus viverra, sed dapibus dolor aliquet. Maecenas sit amet arcu quis nisl lobortis interdum nec et ipsum. Vivamus blandit, velit eu pretium pellentesque, enim diam facilisis velit, sit amet ultrices sem elit in tortor.

Praesent eget erat ac nisl sollicitudin interdum vel a lacus. Curabitur egestas sit amet erat ac mattis. Etiam feugiat ornare semper. Ut eget viverra odio. Integer ut fermentum odio. Cras purus lectus, volutpat at ligula in, lacinia feugiat tellus. Nunc mattis arcu odio, ac pretium tortor tristique id.

Proin interdum ullamcorper mattis. Sed ullamcorper mi non mi ullamcorper, sit amet pretium nisi condimentum. Curabitur vitae consequat arcu. Nulla a feugiat urna, ac pretium urna. Proin suscipit id leo quis maximus. Nam lorem sem, mattis sit amet tortor eget, pharetra porttitor nulla. Integer erat metus, scelerisque vitae orci in, fringilla bibendum metus. Integer sed finibus eros. In pulvinar dui mauris, ut tempor metus bibendum ac. Curabitur eu efficitur eros.

Etiam id magna non erat suscipit sodales non at ipsum. Donec congue faucibus ex, at malesuada arcu tincidunt sed. Nam congue nulla nunc, vel hendrerit urna consectetur sit amet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Praesent quis sagittis nibh. Phasellus tincidunt iaculis rhoncus. Donec quis erat nisi. Duis auctor auctor metus et auctor. Aenean lacinia urna eget ex lobortis maximus. Sed consequat sit amet odio id auctor. Vestibulum pulvinar tellus vitae est pellentesque mollis.

Sed eleifend ante eu ornare tristique. Nunc ac congue felis. Nulla mollis, diam vel pulvinar lobortis, velit massa luctus lacus, sit amet auctor neque mi vitae sem. Vivamus pharetra tortor accumsan lacus faucibus, non pellentesque ligula hendrerit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam eu ligula diam. Duis ac auctor neque. Morbi dignissim vel turpis eu pulvinar. Donec malesuada dictum ipsum non varius. Integer pharetra dictum ipsum sit amet facilisis. Pellentesque sem justo, ultrices ut euismod vel, eleifend in diam. Duis varius, augue porttitor posuere pharetra, eros enim molestie sapien, quis euismod urna metus a risus. In hac habitasse platea dictumst. Duis commodo blandit mauris, in euismod dolor faucibus id.

Quisque ultricies, erat et aliquam malesuada, neque magna convallis eros, consectetur porta nibh velit sed mauris. Vestibulum et ex et velit finibus mattis sed vel orci. In eleifend tincidunt tellus. Vestibulum eu arcu sit amet tortor maximus tincidunt. Phasellus dolor mauris, commodo sit amet neque ac, rutrum pharetra elit. Sed non sagittis tortor. Phasellus aliquam, massa sed interdum scelerisque, est est condimentum urna, non venenatis est leo finibus urna. Fusce bibendum, nulla non venenatis malesuada, metus nisl consequat metus, id ornare velit erat sit amet velit.

Vestibulum vulputate id felis nec porttitor. Nam dignissim erat eu quam dictum, at tincidunt nulla interdum. Phasellus iaculis lectus gravida lacinia dignissim. Pellentesque nec risus eget ligula tincidunt imperdiet eu venenatis arcu. Pellentesque turpis velit, auctor at ornare non, auctor ac augue. Mauris imperdiet nisi in ligula pretium consequat. Fusce eget neque nec risus mattis mollis. Proin dictum neque lobortis magna convallis, quis ultricies tortor placerat. Ut consectetur id lacus nec egestas. Fusce et porta eros. Nulla quis hendrerit orci, a pulvinar nisi. Duis nisl justo, finibus sit amet nibh ac, laoreet aliquam diam. Nullam consequat ex vel ultricies condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Aliquam quis massa tristique, malesuada tortor sit amet, malesuada odio. Pellentesque pellentesque enim nulla, at elementum mi scelerisque non. Nam accumsan in nisi eget sagittis. Nunc sed pretium lectus. Aliquam pretium interdum turpis vel tempor. Praesent eget convallis erat. In luctus imperdiet magna, a volutpat velit aliquet eget. Aenean sit amet molestie ante. Vestibulum nulla neque, lobortis et est non, auctor pharetra mauris. Donec quis ipsum sed ante vestibulum fermentum at ut nulla. Ut a sem diam. Phasellus facilisis facilisis pulvinar. Duis ultrices eros ac efficitur semper. Etiam placerat dui volutpat dictum sollicitudin. Proin a elit in nisi scelerisque auctor. In in ligula quam.

Duis interdum, neque rhoncus tempus vestibulum, libero lectus sagittis tellus, nec porta tellus augue sit amet sem. Donec quis lorem ac tortor tristique ullamcorper. Maecenas vestibulum turpis vitae eleifend vestibulum. Cras consequat id ante vel porta. Praesent dignissim laoreet erat. Sed sagittis dictum consequat. Donec vestibulum sit amet turpis a ornare. Phasellus condimentum dolor volutpat, faucibus nulla ut, ultrices diam. Donec et sollicitudin nisl. Donec semper nisi tristique, efficitur quam vel, malesuada urna. Quisque interdum nisl a sem mattis, eu ultricies nibh posuere. Fusce quis urna non eros lacinia dictum non ac risus. Sed posuere sit amet magna a facilisis.

Nunc porttitor vel magna ullamcorper pulvinar. Praesent hendrerit turpis a risus hendrerit vulputate. Sed consectetur molestie elit, ac laoreet felis dignissim tristique. Fusce aliquet nisi turpis, id ornare ligula fringilla at. Duis nec erat vestibulum, congue dui ac, scelerisque justo. Nulla sed placerat massa. Donec ut massa augue. Cras elementum arcu ut justo bibendum porttitor.`;

export default privacy_policy;