# Generated by Django 5.0.7 on 2024-08-24 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_pages_table_alter_users_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pages',
        ),
    ]
