/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Oscar R (https://sketchfab.com/braidoner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-low-poly-tatooine-skybox-4acf1cbebe674e128b4bf68e9897ae3e
Title: Star Wars - Low Poly Tatooine Skybox
*/

import { animated, easings, useSpring } from '@react-spring/three';
import { useGLTF } from '@react-three/drei';
import React, { useRef, useState } from 'react';
import SkyModel from '../assets/sky.glb';

function Sky({transitioning, currentStage, ...props}) {
  const { nodes, materials } = useGLTF(SkyModel);
  const SkyRef = useRef();
  const [targetScale, setTargetScale] = useState([-0.2784168102533878, -0.2784168102533878, -0.2784168102533878]); // initial coords [-0.2784168102533878, -0.2784168102533878, -0.2784168102533878]
  const [targetPosition, setTargetPosition] = useState([0, -3, -50]); //13.530139730712591, 0, -70.27665056529713
  
  const { scale } = useSpring({
    rotation: targetScale,
    config: { mass: 1, tension: 280, friction: 40, duration: 600, easing: easings.easeInExpo}, // Smooth transition
  });
  const { position } = useSpring({
    position: targetPosition,
    config: { mass: 1, tension: 280, friction: 40, duration: 600, easing: easings.easeInExpo}, // Smooth transition
  });

  return (
    <animated.group {...props} ref={SkyRef} scale={[0.4, 0.4, 0.4]} position={position}>
      <mesh
        geometry={nodes.cloud19_lambert1_0.geometry}
        material={materials.lambert1}
        position={[148.509, -273.404, 146.344]}
        rotation={[-3.135, 0.727, -3.074]}
        scale={4.082}
      />
      <mesh
        geometry={nodes.cloud20_lambert1_0.geometry}
        material={materials.lambert1}
        position={[-190.48, 246.518, 48.081]}
        rotation={[-3.135, -0.199, -0.024]}
        scale={4.082}
      />
      <group rotation={[-Math.PI, 0.737, -Math.PI]}>
        <mesh
          geometry={nodes.polySurface32_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -4.394, 0]}
          scale={[1, 0.668, 1]}
        />
        <mesh geometry={nodes.polySurface21_lambert1_0.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.polySurface17_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, 18.415, -25.146]}
          scale={[1, 0.614, 1.521]}
        />
        <mesh geometry={nodes.polySurface16_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface18_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface15_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface23_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface22_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface20_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface19_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface12_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface14_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface13_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface8_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface10_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface11_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface6_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface7_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.polySurface9_lambert1_0.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.polySurface41_lambert1_0.geometry}
          material={materials.lambert1}
          position={[33.283, -48.732, 2.215]}
          rotation={[0, 0.543, 0]}
          scale={[1, 0.569, 1]}
        />
        <mesh
          geometry={nodes.polySurface42_lambert1_0.geometry}
          material={materials.lambert1}
          position={[30.86, -66.315, 0.344]}
          rotation={[0, 0.543, 0]}
        />
      </group>
      <group rotation={[0, 0.722, 0]}>
        <mesh
          geometry={nodes.polySurface40_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -51.344, 0]}
          scale={[1, 0.646, 1]}
        />
        <mesh
          geometry={nodes.polySurface39_lambert1_0.geometry}
          material={materials.lambert1}
          position={[-273.922, 0, -315.954]}
          rotation={[-Math.PI, -0.01, -Math.PI]}
        />
        <mesh
          geometry={nodes.polySurface38_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -20.37, 0]}
          scale={[1, 0.679, 1]}
        />
        <mesh
          geometry={nodes.polySurface37_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -9.901, 0]}
          scale={[1, 0.65, 1]}
        />
        <mesh
          geometry={nodes.polySurface36_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -12.277, 0]}
          scale={[1, 0.65, 1]}
        />
        <mesh geometry={nodes.polySurface35_lambert1_0.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.polySurface34_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -46.228, 0]}
          scale={[1, 0.562, 1]}
        />
        <mesh
          geometry={nodes.polySurface33_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -35.95, 0]}
          scale={[1, 0.41, 1]}
        />
        <mesh
          geometry={nodes.polySurface31_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -45.705, 0]}
          scale={[1, 0.562, 1]}
        />
        <mesh
          geometry={nodes.polySurface30_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -11.523, 0]}
          scale={[1, 0.878, 1]}
        />
        <mesh geometry={nodes.polySurface29_lambert1_0.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.polySurface28_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -24.009, 0]}
          scale={[1, 0.646, 1]}
        />
        <mesh
          geometry={nodes.polySurface27_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -33.286, -105.886]}
          scale={[1, 0.453, 0.57]}
        />
        <mesh
          geometry={nodes.polySurface26_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -15.151, 0]}
          scale={[1, 0.807, 1]}
        />
        <mesh geometry={nodes.polySurface25_lambert1_0.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.polySurface24_lambert1_0.geometry}
          material={materials.lambert1}
          position={[0, -26.542, 0]}
          scale={[1, 0.553, 1]}
        />
      </group>
      <mesh
        geometry={nodes.tatooine_sky_lambert1_0.geometry}
        material={materials.lambert1}
        position={[0, -0.282, 0]}
        scale={269.618}
      />
    </animated.group>
  )
}

export default Sky;